language: node_js
node_js:
  - "0.12"
  - "0.11"
  - "0.10"
env:
  global:
    - NODE_ENV=test
before_install: |
    case ${TRAVIS_NODE_VERSION} in
        iojs*)
            echo "Not upgrading npm for iojs."
            ;;
        *)
            npm update -g npm
            ;;
    esac